<?php

return [
    'menu_pages' => [
        [
            'label' => 'Pages',
            'route' => null,
            'icon' => null,
            'submenu' => [
                [
                    'label' => 'About',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'About 1', 'route' => 'unify.pages.about.about1'],
                        ['label' => 'About 2', 'route' => 'unify.pages.about.about2'],
                        ['label' => 'About 3', 'route' => 'unify.pages.about.about3'],
                        ['label' => 'About 4', 'route' => 'unify.pages.about.about4'],

                        ['label' => 'About me 1', 'route' => 'unify.pages.about.aboutme1'],
                        ['label' => 'About me 2', 'route' => 'unify.pages.about.aboutme2'],
                        ['label' => 'About me 3', 'route' => 'unify.pages.about.aboutme3'],
                    ],
                ],
                [
                    'label' => 'Portfolios',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'Case Studies 1', 'route' => 'unify.pages.portfolio.casestudy1'],
                        ['label' => 'Case Studies 2', 'route' => 'unify.pages.portfolio.casestudy2'],
                        ['label' => 'Single item 1', 'route' => 'unify.pages.portfolio.item1'],
                        ['label' => 'Single item 2', 'route' => 'unify.pages.portfolio.item2'],
                        ['label' => 'Single item 3', 'route' => 'unify.pages.portfolio.item3'],
                        ['label' => 'Single item 4', 'route' => 'unify.pages.portfolio.item4'],
                        ['label' => 'Single item 5', 'route' => 'unify.pages.portfolio.item5'],
                        ['label' => 'Single item 6', 'route' => 'unify.pages.portfolio.item6'],
                        ['label' => 'Single item 7', 'route' => 'unify.pages.portfolio.item7'],
                        ['label' => 'Single item 8', 'route' => 'unify.pages.portfolio.item8'],
                        ['label' => 'Single item 9', 'route' => 'unify.pages.portfolio.item9'],
                    ],
                ],
                [
                    'label' => 'Login & Signup',
                    'route' => null,
                    'type' => 'col-3',
                    'submenu' => [
                        ['label' => 'Login & Signup', 'route' => 'unify.pages.auth.loginsignup'],
                        ['label' => 'Signup 1', 'route' => 'unify.pages.auth.signup1'],
                        ['label' => 'Signup 2', 'route' => 'unify.pages.auth.signup2'],
                        ['label' => 'Signup 3', 'route' => 'unify.pages.auth.signup3'],
                        ['label' => 'Signup 4', 'route' => 'unify.pages.auth.signup4'],
                        ['label' => 'Signup 5', 'route' => 'unify.pages.auth.signup5'],
                        ['label' => 'Signup 6', 'route' => 'unify.pages.auth.signup6'],
                        ['label' => 'Signup 7', 'route' => 'unify.pages.auth.signup7'],
                        ['label' => 'Signup 8', 'route' => 'unify.pages.auth.signup8'],
                        ['label' => 'Signup 9', 'route' => 'unify.pages.auth.signup9'],
                        ['label' => 'Login 1', 'route' => 'unify.pages.auth.login1'],
                        ['label' => 'Login 2', 'route' => 'unify.pages.auth.login2'],
                        ['label' => 'Login 3', 'route' => 'unify.pages.auth.login3'],
                        ['label' => 'Login 4', 'route' => 'unify.pages.auth.login4'],
                        ['label' => 'Login 5', 'route' => 'unify.pages.auth.login5'],
                        ['label' => 'Login 6', 'route' => 'unify.pages.auth.login6'],
                        ['label' => 'Login 7', 'route' => 'unify.pages.auth.login7'],
                        ['label' => 'Login 8', 'route' => 'unify.pages.auth.login8'],
                        ['label' => 'Login 9', 'route' => 'unify.pages.auth.login9'],
                        ['label' => 'Login 10', 'route' => 'unify.pages.auth.login10'],
                        ['label' => 'Login 11', 'route' => 'unify.pages.auth.login11'],
                        ['label' => 'Login 12', 'route' => 'unify.pages.auth.login12'],
                    ],
                ],
                [
                    'label' => 'Services',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'Services 1', 'route' => 'unify.pages.services.services1'],
                        ['label' => 'Services 2', 'route' => 'unify.pages.services.services2'],
                        ['label' => 'Services 3', 'route' => 'unify.pages.services.services3'],
                        ['label' => 'Services 4', 'route' => 'unify.pages.services.services4'],
                    ],
                ],
                [
                    'label' => 'Search results',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'Grid View', 'route' => 'unify.pages.search.gridview'],
                        ['label' => 'Grid View (with Sidebar)', 'route' => 'unify.pages.search.gridsidebar'],
                        ['label' => 'List View 1', 'route' => 'unify.pages.search.listview1'],
                        ['label' => 'List View 2', 'route' => 'unify.pages.search.listview2'],
                        ['label' => 'List View (with Sidebar)', 'route' => 'unify.pages.search.listsidebar'],
                    ],
                ],
                [
                    'label' => 'Profiles',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'Main', 'route' => 'unify.pages.profile.main'],
                        ['label' => 'User', 'route' => 'unify.pages.profile.user'],
                        ['label' => 'Projects', 'route' => 'unify.pages.profile.projects'],
                        ['label' => 'Comments', 'route' => 'unify.pages.profile.comments'],
                        ['label' => 'History', 'route' => 'unify.pages.profile.history'],
                        ['label' => 'Reviews', 'route' => 'unify.pages.profile.reviews'],
                        ['label' => 'Settings', 'route' => 'unify.pages.profile.settings'],
                        ['label' => 'Contacts 1', 'route' => 'unify.pages.profile.contacts1'],
                        ['label' => 'Contacts 1 (full width)', 'route' => 'unify.pages.profile.contacts1fw'],
                        ['label' => 'Contacts 2', 'route' => 'unify.pages.profile.contacts2'],
                        ['label' => 'Contacts 2 (full width)', 'route' => 'unify.pages.profile.contacts2fw'],
                    ],
                ],
                [
                    'label' => 'Contacts',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'Contacts 1', 'route' => 'unify.pages.contacts.contacts1'],
                        ['label' => 'Contacts 2', 'route' => 'unify.pages.contacts.contacts2'],
                        ['label' => 'Contacts 3', 'route' => 'unify.pages.contacts.contacts3'],
                        ['label' => 'Contacts 4', 'route' => 'unify.pages.contacts.contacts4'],
                        ['label' => 'Contacts 5', 'route' => 'unify.pages.contacts.contacts5'],
                        ['label' => 'Contacts 6', 'route' => 'unify.pages.contacts.contacts6'],
                        ['label' => 'Contacts 7', 'route' => 'unify.pages.contacts.contacts7'],
                        ['label' => 'Contacts 8', 'route' => 'unify.pages.contacts.contacts8'],
                    ],
                ],
                [
                    'label' => 'Jobs',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'Jobs', 'route' => 'unify.pages.jobs.jobs'],
                        ['label' => 'Jobs Description', 'route' => 'unify.pages.jobs.description'],
                    ],
                ],
                [
                    'label' => 'Error 404',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'ERROR 404 1', 'route' => 'unify.pages.error404.page4041'],
                        ['label' => 'ERROR 404 2', 'route' => 'unify.pages.error404.page4042'],
                    ],
                ],
                [
                    'label' => 'FAQ',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'FAQ 1', 'route' => 'unify.pages.faq.faq1'],
                        ['label' => 'FAQ 2', 'route' => 'unify.pages.faq.faq2'],
                    ],
                ],
                [
                    'label' => 'Others',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'Clients', 'route' => 'unify.pages.other.clients'],
                        ['label' => 'Terms', 'route' => 'unify.pages.other.terms'],
                        ['label' => 'Cookies', 'route' => 'unify.pages.other.cookies'],
                        ['label' => 'Invoice', 'route' => 'unify.pages.other.invoice'],
                        ['label' => 'Pricing', 'route' => 'unify.pages.other.pricing'],
                        ['label' => 'Coming Soon', 'route' => 'unify.pages.other.comingsoon'],
                    ],
                ],
            ],
        ],
    ],
];
