<?php

return [
    'menu_pages' => [
        [
            'label' => 'Pages',
            'route' => null,
            'icon' => null,
            'submenu' => [
                ['label' => 'Headers', 'route' => 'unify.templates.main.pages.headers.index'],
                [
                    'label' => 'About',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'About 1', 'route' => 'unify.templates.main.pages.about.about1'],
                        ['label' => 'About 2', 'route' => 'unify.templates.main.pages.about.about2'],
                        ['label' => 'About 3', 'route' => 'unify.templates.main.pages.about.about3'],
                        ['label' => 'About 4', 'route' => 'unify.templates.main.pages.about.about4'],

                        ['label' => 'About me 1', 'route' => 'unify.templates.main.pages.about.aboutme1'],
                        ['label' => 'About me 2', 'route' => 'unify.templates.main.pages.about.aboutme2'],
                        ['label' => 'About me 3', 'route' => 'unify.templates.main.pages.about.aboutme3'],
                    ],
                ],
                [
                    'label' => 'Portfolios',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'Case Studies 1', 'route' => 'unify.templates.main.pages.portfolio.casestudy1'],
                        ['label' => 'Case Studies 2', 'route' => 'unify.templates.main.pages.portfolio.casestudy2'],
                        ['label' => 'Single item 1', 'route' => 'unify.templates.main.pages.portfolio.singleitem1'],
                        ['label' => 'Single item 2', 'route' => 'unify.templates.main.pages.portfolio.singleitem2'],
                        ['label' => 'Single item 3', 'route' => 'unify.templates.main.pages.portfolio.singleitem3'],
                        ['label' => 'Single item 4', 'route' => 'unify.templates.main.pages.portfolio.singleitem4'],
                        ['label' => 'Single item 5', 'route' => 'unify.templates.main.pages.portfolio.singleitem5'],
                        ['label' => 'Single item 6', 'route' => 'unify.templates.main.pages.portfolio.singleitem6'],
                        ['label' => 'Single item 7', 'route' => 'unify.templates.main.pages.portfolio.singleitem7'],
                        ['label' => 'Single item 8', 'route' => 'unify.templates.main.pages.portfolio.singleitem8'],
                        ['label' => 'Single item 9', 'route' => 'unify.templates.main.pages.portfolio.singleitem9'],
                    ],
                ],
                [
                    'label' => 'Login & Signup',
                    'route' => null,
                    'type' => 'col-3',
                    'submenu' => [
                        ['label' => 'Login & Signup', 'route' => 'unify.templates.main.pages.auth.loginandsignup1'],
                        ['label' => 'Signup 1', 'route' => 'unify.templates.main.pages.auth.signup1'],
                        ['label' => 'Signup 2', 'route' => 'unify.templates.main.pages.auth.signup2'],
                        ['label' => 'Signup 3', 'route' => 'unify.templates.main.pages.auth.signup3'],
                        ['label' => 'Signup 4', 'route' => 'unify.templates.main.pages.auth.signup4'],
                        ['label' => 'Signup 5', 'route' => 'unify.templates.main.pages.auth.signup5'],
                        ['label' => 'Signup 6', 'route' => 'unify.templates.main.pages.auth.signup6'],
                        ['label' => 'Signup 7', 'route' => 'unify.templates.main.pages.auth.signup7'],
                        ['label' => 'Signup 8', 'route' => 'unify.templates.main.pages.auth.signup8'],
                        ['label' => 'Signup 9', 'route' => 'unify.templates.main.pages.auth.signup9'],
                        ['label' => 'Login 1', 'route' => 'unify.templates.main.pages.auth.login1'],
                        ['label' => 'Login 2', 'route' => 'unify.templates.main.pages.auth.login2'],
                        ['label' => 'Login 3', 'route' => 'unify.templates.main.pages.auth.login3'],
                        ['label' => 'Login 4', 'route' => 'unify.templates.main.pages.auth.login4'],
                        ['label' => 'Login 5', 'route' => 'unify.templates.main.pages.auth.login5'],
                        ['label' => 'Login 6', 'route' => 'unify.templates.main.pages.auth.login6'],
                        ['label' => 'Login 7', 'route' => 'unify.templates.main.pages.auth.login7'],
                        ['label' => 'Login 8', 'route' => 'unify.templates.main.pages.auth.login8'],
                        ['label' => 'Login 9', 'route' => 'unify.templates.main.pages.auth.login9'],
                        ['label' => 'Login 10', 'route' => 'unify.templates.main.pages.auth.login10'],
                        ['label' => 'Login 11', 'route' => 'unify.templates.main.pages.auth.login11'],
                        ['label' => 'Login 12', 'route' => 'unify.templates.main.pages.auth.login12'],
                    ],
                ],
                [
                    'label' => 'Services',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'Services 1', 'route' => 'unify.templates.main.pages.services.services1'],
                        ['label' => 'Services 2', 'route' => 'unify.templates.main.pages.services.services2'],
                        ['label' => 'Services 3', 'route' => 'unify.templates.main.pages.services.services3'],
                        ['label' => 'Services 4', 'route' => 'unify.templates.main.pages.services.services4'],
                    ],
                ],
                [
                    'label' => 'Search results',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'Grid View', 'route' => 'unify.templates.main.pages.search.grid1'],
                        ['label' => 'Grid View (with Sidebar)', 'route' => 'unify.templates.main.pages.search.gridleftsidebar1'],
                        ['label' => 'List View 1', 'route' => 'unify.templates.main.pages.search.list1'],
                        ['label' => 'List View 2', 'route' => 'unify.templates.main.pages.search.list2'],
                        ['label' => 'List View (with Sidebar)', 'route' => 'unify.templates.main.pages.search.listleftsidebar1'],
                    ],
                ],
                [
                    'label' => 'Profiles',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'Main', 'route' => 'unify.templates.main.pages.profile.main1'],
                        ['label' => 'Profile', 'route' => 'unify.templates.main.pages.profile.profile1'],
                        ['label' => 'Contacts 1', 'route' => 'unify.templates.main.pages.profile.userscontact1'],
                        ['label' => 'Contacts 1 (full width)', 'route' => 'unify.templates.main.pages.profile.userscontact1fullwidth'],
                        ['label' => 'Contacts 2', 'route' => 'unify.templates.main.pages.profile.userscontact2'],
                        ['label' => 'Contacts 2 (full width)', 'route' => 'unify.templates.main.pages.profile.userscontact2fullwidth'],
                        ['label' => 'Projects', 'route' => 'unify.templates.main.pages.profile.projects1'],
                        ['label' => 'Comments', 'route' => 'unify.templates.main.pages.profile.comments1'],
                        ['label' => 'Reviews', 'route' => 'unify.templates.main.pages.profile.reviews1'],
                        ['label' => 'History', 'route' => 'unify.templates.main.pages.profile.history1'],
                        ['label' => 'Settings', 'route' => 'unify.templates.main.pages.profile.settings1'],
                    ],
                ],
                [
                    'label' => 'Contacts',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'Contacts 1', 'route' => 'unify.templates.main.pages.contacts.contacts1'],
                        ['label' => 'Contacts 2', 'route' => 'unify.templates.main.pages.contacts.contacts2'],
                        ['label' => 'Contacts 3', 'route' => 'unify.templates.main.pages.contacts.contacts3'],
                        ['label' => 'Contacts 4', 'route' => 'unify.templates.main.pages.contacts.contacts4'],
                        ['label' => 'Contacts 5', 'route' => 'unify.templates.main.pages.contacts.contacts5'],
                        ['label' => 'Contacts 6', 'route' => 'unify.templates.main.pages.contacts.contacts6'],
                        ['label' => 'Contacts 7', 'route' => 'unify.templates.main.pages.contacts.contacts7'],
                        ['label' => 'Contacts 8', 'route' => 'unify.templates.main.pages.contacts.contacts8'],
                    ],
                ],
                [
                    'label' => 'Jobs',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'Jobs', 'route' => 'unify.templates.main.pages.jobs.jobs1'],
                        ['label' => 'Jobs Description', 'route' => 'unify.templates.main.pages.jobs.jobsdescriptionrightsidebar1'],
                    ],
                ],
                [
                    'label' => 'Error 404',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'ERROR 404 1', 'route' => 'unify.templates.specialtypages.404.4041'],
                        ['label' => 'ERROR 404 2', 'route' => 'unify.templates.specialtypages.404.4042'],
                    ],
                ],
                [
                    'label' => 'FAQ',
                    'route' => null,
                    'submenu' => [
                        ['label' => 'FAQ 1', 'route' => 'unify.templates.main.pages.faq.faq1'],
                        ['label' => 'FAQ 2', 'route' => 'unify.templates.main.pages.faq.faq2'],
                    ],
                ],
                [
                    'label' => 'Others',
                    'route' => null,
                    'type' => 'dual-column',
                    'submenu' => [
                        ['label' => 'Clients', 'route' => 'unify.templates.main.pages.clients.clients1'],
                        ['label' => 'Terms', 'route' => 'unify.templates.main.pages.terms.terms1'],
                        ['label' => 'Cookies', 'route' => 'unify.templates.main.pages.cookies.cookies1'],
                        ['label' => 'Invoice', 'route' => 'unify.templates.main.pages.invoice.invoice1'],
                        ['label' => 'Pricing', 'route' => 'unify.templates.main.pages.pricing.pricing1'],
                        ['label' => 'Coming Soon', 'route' => 'unify.templates.specialtypages.coming-soon.pagecomingsoon1', 'target' => '_blank'],
                    ],
                ],
            ],
        ],
    ],
];
